# -*- coding: utf-8 -*-
"""Caso_accidente_aereo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BLH96G1nGwElWzmUyCR8i66J87_JdwSi
"""

import pandas as pd
import numpy as np

#Facilitar a lectura de los numerosos valores
np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

air_accident = pd.read_csv("train.csv")
air_accident.head(10)

air_accident_features = air_accident.copy()
air_accident_labels = air_accident_features.pop('survived')

"""creamos un modelo que implementa la lógica de preprocesamiento utilizando la API funcional de Keras."""

#Creamos una entrada simbolica
input = tf.keras.Input(shape=(), dtype=tf.float32)
#Hacemos un calculo usando..
result = 2*input + 1
#Este resultado no va a tener valor
result

"""construimos un conjunto de objetos keras.Input simbólicos, haciendo coincidir los nombres y tipos de datos de las columnas del CSV."""

inputs = {}
for name, column in air_accident_features.items():
  dtype = column.dtype
  if dtype == object:
    dtype = tf.string
  else:
    dtype = tf.float32
  inputs[name] = tf.keras.Input(shape=(1,), name=name, dtype=dtype)
inputs

"""concatenamos las entradas numéricas juntas y ejecutamos a través de una capa de normalización"""

numeric_inputs = {name:input for name,input in inputs.items()
                  if input.dtype==tf.float32}
x = layers.Concatenate()(list(numeric_inputs.values()))
norm = preprocessing.Normalization()
norm.adapt(np.array(air_accident[numeric_inputs.keys()]))
all_numeric_inputs = norm(x)
all_numeric_inputs

"""1. recopilamos todos los resultados del preprocesamiento simbólico, para concatenarlos posteriormente.
2. usamos la función preprocessing.StringLookup para mapear desde cadenas a índices enteros en un vocabulario.
3. concatenar todas las entradas preprocesadas juntas y construimos un modelo que maneja el preprocesamiento.

"""

preprocessed_inputs = [all_numeric_inputs]

for name, input in inputs.items():
  if input.dtype == tf.float32:
    continue
  lookup = preprocessing.StringLookup(vocabulary=np.unique(air_accident_features[name]))
  one_hot = preprocessing.CategoryEncoding(max_tokens=lookup.vocab_size())
  x = lookup(input)
  x = one_hot(x)
  preprocessed_inputs.append(x)

preprocessed_inputs_cat = layers.Concatenate()(preprocessed_inputs)
air_accident_preprocessing = tf.keras.Model(inputs, preprocessed_inputs_cat)
tf.keras.utils.plot_model(model = air_accident_preprocessing , rankdir="LR", dpi=72, show_shapes=True)

"""convertimos los datos **panda** en un diccionario de tensores"""

air_accident_features_dict = {name: np.array(value) 
                         for name, value in air_accident_features.items()}

"""Dividimos el primer ejemplo de entrenamiento y lo pasamos a un modelo de preprocesamiento"""

features_dict = {name:values[:1] for name, values in air_accident_features_dict.items()}
air_accident_preprocessing(features_dict)

"""construimos el modelo
pasamos el diccionario de entidades como x y la etiqueta como y
"""

def air_accident_model(preprocessing_head, inputs):
  body = tf.keras.Sequential([
    layers.Dense(64),
    layers.Dense(1)
  ])
  preprocessed_inputs = preprocessing_head(inputs)
  result = body(preprocessed_inputs)
  model = tf.keras.Model(inputs, result)
  model.compile(loss=tf.losses.BinaryCrossentropy(from_logits=True),
                optimizer=tf.optimizers.Adam())
  return model
air_accident_model = air_accident_model(air_accident_preprocessing, inputs)

air_accident_model.fit(x=air_accident_features_dict, y=air_accident_labels, epochs=10)

"""guardamos el modelo"""

air_accident_model.save('test')
reloaded = tf.keras.models.load_model('test')

features_dict = {name:values[:1] for name, values in air_accident_features_dict.items()}

before = air_accident_model(features_dict)
after = reloaded(features_dict)
assert (before-after)<1e-3
print(before)
print(after)

import itertools

def slices(features):
  for i in itertools.count():
    #Para cada característica, tomamos el índice `i`
    example = {name:values[i] for name, values in features.items()}
    yield example
#Ejecutamos primer ejemplo
for example in slices(titanic_features_dict):
  for name, value in example.items():
    print(f"{name:19s}: {value}")
  break

"""iteramos sobre un **tf.data.Dataset**"""

features_ds = tf.data.Dataset.from_tensor_slices(titanic_features_dict)

for example in features_ds:
  for name, value in example.items():
    print(f"{name:19s}: {value}")
  break

air_accident_ds = tf.data.Dataset.from_tensor_slices((air_accident_features_dict, air_accident_labels))
air_accident_batches = air_accident_ds.shuffle(len(air_accident_labels)).batch(32)
air_accident_model.fit(air_accident_batches, epochs=5)

"""leemos los datos CSV del archivo y cree **untf.data.Dataset**"""

air_accident_file_path = tf.keras.utils.get_file("train.csv", "https://storage.googleapis.com/tf-datasets/air_accident/train.csv")

air_accident_csv_ds = tf.data.experimental.make_csv_dataset(
    air_accident_file_path,
    batch_size=5, # Artificially small to make examples easier to show.
    label_name='survived',
    num_epochs=1,
    ignore_errors=True,)

for batch, label in air_accident_csv_ds.take(1):
  for key, value in batch.items():
    print(f"{key:20s}: {value}")
  print()
  print(f"{'label':20s}: {label}")